"""Visualisation helpers for demo notebooks and saved figures."""
from .columbia import (
    apply_columbia_style,
    COLUMBIA_BLUE,
    NAVY,
    DARK,
    WHITE,
    SLATE,
    ORANGE,
    GREEN,
    PANEL,
    CLOUD,
    plot_price_strip,
    plot_error_bar,
    plot_convergence,
    plot_L_sensitivity,
    plot_error_vs_runtime,
)
from .notebook_runtime import (
    ensure_repo_root_on_path,
    error_zoom_bounds,
    locate_repo_root,
    night_style,
    sci,
    style_table,
    timed_call,
    timed_median_ms,
    timeit_strip,
)

__all__ = [
    "apply_columbia_style",
    "COLUMBIA_BLUE",
    "NAVY",
    "DARK",
    "WHITE",
    "SLATE",
    "ORANGE",
    "GREEN",
    "PANEL",
    "CLOUD",
    "plot_price_strip",
    "plot_error_bar",
    "plot_convergence",
    "plot_L_sensitivity",
    "plot_error_vs_runtime",
    "ensure_repo_root_on_path",
    "error_zoom_bounds",
    "locate_repo_root",
    "night_style",
    "sci",
    "style_table",
    "timed_call",
    "timed_median_ms",
    "timeit_strip",
]
