"""Sv32 PyFENG surface regression test against frozen reference JSON.

The reference surface covers 7 strikes x 4 maturities and was generated by
scripts/generate_sv32_pyfeng_surface_reference.py using pyfeng_fft. It is a
backend regression target, not a printed paper table.

Three engines are tested:
- pyfeng_fft: must reproduce the frozen surface to atol=5e-4 (self-consistency).
- cos_improved: must agree to atol=1.5e-3.
- lewis: tested only on the two longer-maturity columns (T=0.5, 1.0); deep-OTM
  rows at short maturities can require extremely wide integration ranges.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

import foureng as fe
from foureng.pricers.lewis import lewis_call_prices

pytestmark = [pytest.mark.derived_reference, pytest.mark.adapter]

pyfeng = pytest.importorskip("pyfeng", reason="pyfeng not installed  -  sv32 tests require it")

_REF_PATH = Path(__file__).resolve().parents[1] / "refs" / "sv32_pyfeng_surface_reference.json"


def _load():
    return json.loads(_REF_PATH.read_text())


def _make_params(ref):
    return fe.Sv32Params(
        v0=ref["v0"],
        kappa=ref["kappa"],
        theta=ref["theta"],
        nu=ref["nu"],
        rho=ref["rho"],
    )


def _build_surface(method, ref, params, strikes, maturities):
    got = np.empty((len(strikes), len(maturities)), dtype=float)
    for j, T in enumerate(maturities):
        fwd = fe.ForwardSpec(
            S0=ref["spot"],
            r=ref["risk_free_rate"],
            q=ref["dividend_yield"],
            T=float(T),
        )
        if method == "lewis":
            phi = lambda u, _fwd=fwd, _p=params: fe.sv32_cf(u, _fwd, _p)
            got[:, j] = lewis_call_prices(
                phi,
                strikes,
                spot=fwd.S0,
                texp=fwd.T,
                intr=fwd.r,
                divr=fwd.q,
                method="trapz",
                u_max=300.0,
                n_u=32768,
            )
        else:
            got[:, j] = fe.price_strip("sv32", method, strikes, fwd, params)
    return got


def test_sv32_pyfeng_fft_reproduces_frozen_surface():
    """pyfeng_fft must reproduce the frozen reference surface to atol=5e-4."""
    ref = _load()
    params = _make_params(ref)
    strikes = np.array(ref["strikes"], dtype=float)
    maturities = np.array(ref["maturities_years"], dtype=float)
    expected = np.array(ref["call_price_surface"], dtype=float)
    atol = ref["pyfeng_fft_self_tolerance"]

    got = _build_surface("pyfeng_fft", ref, params, strikes, maturities)
    np.testing.assert_allclose(got, expected, atol=atol, rtol=0.0)


def test_sv32_cos_improved_agrees_with_frozen_surface():
    """cos_improved must agree with the frozen reference surface to atol=1.5e-3."""
    ref = _load()
    params = _make_params(ref)
    strikes = np.array(ref["strikes"], dtype=float)
    maturities = np.array(ref["maturities_years"], dtype=float)
    expected = np.array(ref["call_price_surface"], dtype=float)
    atol = ref["cos_improved_tolerance"]

    got = _build_surface("cos_improved", ref, params, strikes, maturities)
    np.testing.assert_allclose(got, expected, atol=atol, rtol=0.0)


def test_sv32_lewis_agrees_with_frozen_surface_long_maturities():
    """Lewis agrees with the frozen surface to atol=1.5e-3 for T>=0.5.

    Short-maturity deep-OTM rows require impractically large u_max for Lewis;
    those are covered by pyfeng_fft and cos_improved above.
    """
    ref = _load()
    params = _make_params(ref)
    strikes = np.array(ref["strikes"], dtype=float)
    maturities = np.array(ref["maturities_years"], dtype=float)
    expected = np.array(ref["call_price_surface"], dtype=float)
    atol = ref["cos_improved_tolerance"]

    # Test only T >= 0.5
    long_mask = maturities >= 0.5
    maturities_long = maturities[long_mask]
    expected_long = expected[:, long_mask]

    got = _build_surface("lewis", ref, params, strikes, maturities_long)
    np.testing.assert_allclose(got, expected_long, atol=atol, rtol=0.0)
