"""Patch cell 24 of demo.ipynb with the correct §6 setup source."""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
NB   = ROOT / "notebooks" / "demo.ipynb"

NEW_SRC = (
    "import time, pathlib, sys, importlib\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "# ── Ensure the adaptive filtered-COS extension is importable ──────────\n"
    "# spectral_filters and experiments were added after PyPI v0.2.0.\n"
    "# If the currently-loaded foureng doesn't have them, evict the stale\n"
    "# module cache and reload from the repo root (editable install).\n"
    "def _try_import_extension():\n"
    "    try:\n"
    "        from foureng.utils.spectral_filters import COSFilterSpec  # noqa\n"
    "        from foureng.experiments.cos_filter_grid_search import (   # noqa\n"
    "            FilterGridCandidate, run_filtered_cos_grid_search,\n"
    "            select_fastest_under_tolerance,\n"
    "        )\n"
    "        return True\n"
    "    except (ImportError, ModuleNotFoundError):\n"
    "        return False\n"
    "\n"
    "if not _try_import_extension():\n"
    "    _here = pathlib.Path('.').resolve()\n"
    "    _root = _here\n"
    "    for _ in range(6):\n"
    "        if (_root / 'pyproject.toml').exists():\n"
    "            break\n"
    "        _root = _root.parent\n"
    "    for _k in [k for k in sys.modules\n"
    "               if k == 'foureng' or k.startswith('foureng.')]:\n"
    "        del sys.modules[_k]\n"
    "    if str(_root) not in sys.path:\n"
    "        sys.path.insert(0, str(_root))\n"
    "    importlib.invalidate_caches()\n"
    "    if not _try_import_extension():\n"
    "        raise ImportError(\n"
    "            'foureng.utils.spectral_filters is not importable. '\n"
    "            'Run: pip install -e . from the repo root.'\n"
    "        )\n"
    "\n"
    "from foureng.utils.spectral_filters import COSFilterSpec\n"
    "from foureng.experiments.cos_filter_grid_search import (\n"
    "    FilterGridCandidate, run_filtered_cos_grid_search, select_fastest_under_tolerance,\n"
    ")\n"
    "from foureng.models.bsm    import BsmParams\n"
    "from foureng.models.heston import HestonParams\n"
    "from foureng.models.variance_gamma import VGParams\n"
    "from foureng.models.cgmy   import CgmyParams\n"
    "from foureng.models.kou    import KouParams\n"
    "from foureng.pipeline import price_strip\n"
    "from foureng.pricers.cos import recommended_cos_policy\n"
    "from foureng.utils.grids import COSGridPolicy\n"
    "\n"
    "_OUT_DIR = pathlib.Path('benchmarks/mc_vs_fourier_methods/outputs')\n"
    "_FIG_DIR = _OUT_DIR / 'figures'\n"
    "_OUT_DIR.mkdir(parents=True, exist_ok=True)\n"
    "_FIG_DIR.mkdir(parents=True, exist_ok=True)\n"
    "_TOL = 1e-6\n"
    "\n"
    "STRESS_CASES = [\n"
    "    dict(case_name='BSM_T1',    model='bsm',\n"
    "         fwd=ForwardSpec(S0=100, r=0.03, q=0.01, T=1.0),\n"
    "         params=BsmParams(sigma=0.25), strikes=np.linspace(80, 120, 13)),\n"
    "    dict(case_name='Heston_T1', model='heston',\n"
    "         fwd=ForwardSpec(S0=100, r=0.03, q=0.01, T=1.0),\n"
    "         params=HestonParams(kappa=2.0, theta=0.04, nu=0.5, rho=-0.7, v0=0.04),\n"
    "         strikes=np.linspace(80, 120, 13)),\n"
    "    dict(case_name='VG_T01',    model='vg',\n"
    "         fwd=ForwardSpec(S0=100, r=0.1, q=0.0, T=0.1),\n"
    "         params=VGParams(sigma=0.12, nu=0.2, theta=-0.14),\n"
    "         strikes=np.linspace(70, 130, 25)),\n"
    "    dict(case_name='VG_T1',     model='vg',\n"
    "         fwd=ForwardSpec(S0=100, r=0.05, q=0.0, T=1.0),\n"
    "         params=VGParams(sigma=0.12, nu=0.2, theta=-0.14),\n"
    "         strikes=np.linspace(80, 120, 13)),\n"
    "    dict(case_name='CGMY_T025', model='cgmy',\n"
    "         fwd=ForwardSpec(S0=100, r=0.04, q=0.0, T=0.25),\n"
    "         params=CgmyParams(C=1.0, G=5.0, M=10.0, Y=0.5),\n"
    "         strikes=np.linspace(80, 120, 13)),\n"
    "    dict(case_name='Kou_T05',   model='kou',\n"
    "         fwd=ForwardSpec(S0=100, r=0.04, q=0.0, T=0.5),\n"
    "         params=KouParams(sigma=0.16, lam=0.30, p=0.40, eta1=10.0, eta2=6.0),\n"
    "         strikes=np.linspace(80, 120, 13)),\n"
    "]\n"
    "\n"
    "def _oracle_policy(model):\n"
    "    trunc = 'heuristic' if model == 'vg' else 'tolerance'\n"
    "    return COSGridPolicy(mode='benchmark', truncation=trunc, centered=True,\n"
    "        dx_target=0.001, L=14.0, eps_trunc=1e-12,\n"
    "        min_N=64, max_N=16384, width_fallback=0.0)\n"
    "\n"
    "def _candidate_set(policy):\n"
    "    return [\n"
    "        FilterGridCandidate('junike_no_filter',  policy, None),\n"
    "        FilterGridCandidate('junike_fejer',       policy, COSFilterSpec('fejer')),\n"
    "        FilterGridCandidate('junike_lanczos',     policy, COSFilterSpec('lanczos')),\n"
    "        FilterGridCandidate('junike_raised_cos', policy, COSFilterSpec('raised_cosine')),\n"
    "        FilterGridCandidate('junike_exp_p4',      policy, COSFilterSpec('exponential', order=4)),\n"
    "        FilterGridCandidate('junike_exp_p8',      policy, COSFilterSpec('exponential', order=8)),\n"
    "        FilterGridCandidate('junike_exp_p12',     policy, COSFilterSpec('exponential', order=12)),\n"
    "    ]\n"
    "\n"
    "print('Section 6 setup complete. Running over', len(STRESS_CASES), 'stress cases ...')\n"
)

nb = json.loads(NB.read_text())
nb['cells'][24]['source'] = NEW_SRC
NB.write_text(json.dumps(nb, indent=1, ensure_ascii=False))
print("Cell 24 patched successfully.")
