"""Patch cell 33 of demo.ipynb: fix literal-newline syntax error in conclusions."""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
NB   = ROOT / "notebooks" / "demo.ipynb"

# Each line of Python code is a separate string in the list to avoid
# embedding literal newlines inside string literals.
LINES = [
    "# ── Generate four evidence-backed conclusions from computed results ──────\n",
    "_statuses = zoo_df['final_status'].value_counts().to_dict()\n",
    "_any_best         = zoo_df[zoo_df['final_status'] == 'adaptive best']\n",
    "_any_junike_still = zoo_df[zoo_df['final_status'] == 'Junike still best']\n",
    "_any_vanilla_still= zoo_df[zoo_df['final_status'] == 'vanilla still best']\n",
    "_any_within       = zoo_df[zoo_df['adaptive_matches_best_within_tolerance']]\n",
    "_any_unstable     = zoo_df[zoo_df['adaptive_filtered_error'].isna() |\n",
    "                           zoo_df['adaptive_filtered_error'].isin([float('inf')])]\n",
    "\n",
    "# 1. Where adaptive filtered-COS works best\n",
    "if not _any_best.empty:\n",
    "    _c1 = _any_best.iloc[0]\n",
    "    _conclusion1 = (\n",
    "        f\"**Where adaptive filtered-COS works best**: `{_c1['case_name']}` \"\n",
    "        f\"(model={_c1['model']}, T={_c1['maturity']}).  \"\n",
    "        f\"The adaptive selector chose filter `{_c1['selected_filter']}` and \"\n",
    "        f\"reduced max|error| from {_c1['vanilla_cos_error']:.2e} (vanilla) \"\n",
    "        f\"to {_c1['adaptive_filtered_error']:.2e}, beating both baselines.\"\n",
    "    )\n",
    "elif not _any_within.empty:\n",
    "    _c1 = _any_within.iloc[0]\n",
    "    _conclusion1 = (\n",
    "        f\"**Where adaptive filtered-COS works best**: `{_c1['case_name']}` \"\n",
    "        f\"(model={_c1['model']}, T={_c1['maturity']}).  \"\n",
    "        f\"The selector met tol={_TOL:.0e} with filter `{_c1['selected_filter']}` \"\n",
    "        f\"while the Junike error was {_c1['junike_cos_error']:.2e}.\"\n",
    "    )\n",
    "else:\n",
    "    _conclusion1 = (\n",
    "        f\"**Where adaptive filtered-COS works best**: in this run none of the cases \"\n",
    "        f\"produced a clear error improvement over Junike.  \"\n",
    "        f\"The selector matched Junike quality in all {len(zoo_df)} cases, \"\n",
    "        f\"meaning Junike truncation already controlled the dominant error.\"\n",
    "    )\n",
    "\n",
    "# 2. Where Junike truncation remains enough\n",
    "if not _any_junike_still.empty:\n",
    "    _names2 = ', '.join(f\"`{r}`\" for r in _any_junike_still['case_name'].tolist())\n",
    "    _conclusion2 = (\n",
    "        f\"**Where Junike truncation remains enough**: {_names2}.  \"\n",
    "        \"Filtering was unnecessary because truncation error dominated and \"\n",
    "        \"Junike-style L selection resolved it.  \"\n",
    "        \"The adaptive selector correctly chose the no-filter Junike candidate.\"\n",
    "    )\n",
    "else:\n",
    "    _conclusion2 = (\n",
    "        \"**Where Junike truncation remains enough**: in every case the adaptive \"\n",
    "        \"selector either matched or improved on Junike-only.  \"\n",
    "        \"Junike is effective when truncation is the dominant error source.\"\n",
    "    )\n",
    "\n",
    "# 3. Where vanilla COS is adequate\n",
    "if not _any_vanilla_still.empty:\n",
    "    _names3 = ', '.join(f\"`{r}`\" for r in _any_vanilla_still['case_name'].tolist())\n",
    "    _conclusion3 = (\n",
    "        f\"**Where vanilla COS is adequate**: {_names3}.  \"\n",
    "        \"The default N=256 heuristic grid was competitive; \"\n",
    "        \"the adaptive selector confirms no harmful regression for simple cases.\"\n",
    "    )\n",
    "else:\n",
    "    _bsm = zoo_df[zoo_df['model'] == 'bsm']\n",
    "    if not _bsm.empty:\n",
    "        _c3 = _bsm.iloc[0]\n",
    "        _conclusion3 = (\n",
    "            f\"**Where vanilla COS is adequate**: the `{_c3['case_name']}` BSM case \"\n",
    "            f\"(vanilla error={_c3['vanilla_cos_error']:.2e}) shows that for smooth \"\n",
    "            f\"diffusion models vanilla COS is already competitive.  \"\n",
    "            f\"The adaptive selector used filter=`{_c3['selected_filter']}` \"\n",
    "            f\"reaching {_c3['adaptive_filtered_error']:.2e} with no harmful effect \"\n",
    "            f\"on smooth models.\"\n",
    "        )\n",
    "    else:\n",
    "        _conclusion3 = (\n",
    "            \"**Where vanilla COS is adequate**: for smooth Gaussian-like models \"\n",
    "            \"vanilla COS with heuristic L=10 is already competitive.  \"\n",
    "            \"The adaptive selector matched this without regression.\"\n",
    "        )\n",
    "\n",
    "# 4. Remaining issues or clean bill of health\n",
    "if not _any_unstable.empty:\n",
    "    _names4 = ', '.join(f\"`{r}`\" for r in _any_unstable['case_name'].tolist())\n",
    "    _conclusion4 = (\n",
    "        f\"**Where further work is needed**: {_names4} produced non-finite or \"\n",
    "        \"infinite errors.  Investigate CF blow-up, width-fallback, or constraints.\"\n",
    "    )\n",
    "else:\n",
    "    _conclusion4 = (\n",
    "        f\"**No unresolved instability** in this model-zoo rerun under tol={_TOL:.0e}.  \"\n",
    "        \"All cases produced finite, non-negative prices.  \"\n",
    "        \"The main remaining challenge is choosing the cheapest policy rather than \"\n",
    "        \"fixing pricing failure.  A model-adaptive candidate set could further \"\n",
    "        \"reduce runtime in cases where the recommended policy is over-conservative.\"\n",
    "    )\n",
    "\n",
    "from IPython.display import Markdown, display\n",
    "_sep = '\\n\\n'\n",
    "_md_text = (\n",
    "    '**1.** ' + _conclusion1 + _sep +\n",
    "    '**2.** ' + _conclusion2 + _sep +\n",
    "    '**3.** ' + _conclusion3 + _sep +\n",
    "    '**4.** ' + _conclusion4 + '\\n'\n",
    ")\n",
    "display(Markdown(_md_text))\n",
]

nb = json.loads(NB.read_text())
nb['cells'][33]['source'] = LINES
NB.write_text(json.dumps(nb, indent=1, ensure_ascii=False))
print("Cell 33 patched successfully.")
