"""Generate the frozen Sv32 PyFENG surface reference JSON.

Run this script once to (re)generate tests/refs/sv32_pyfeng_surface_reference.json.
Do not run this inside pytest  -  tests read the frozen JSON only.

Usage:
    python scripts/generate_sv32_pyfeng_surface_reference.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

# Ensure repo root is on path when run directly
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import pyfeng  # type: ignore
import foureng as fe

_OUT_PATH = (
    Path(__file__).resolve().parents[1] / "tests" / "refs" / "sv32_pyfeng_surface_reference.json"
)

S0 = 100.0
r = 0.0
q = 0.0
params = fe.Sv32Params(v0=0.06, kappa=20.48, theta=0.218, nu=3.20, rho=-0.99)
strikes = np.array([80.0, 90.0, 95.0, 100.0, 105.0, 110.0, 120.0])
maturities = np.array([1.0 / 12.0, 0.25, 0.5, 1.0])

surface = np.empty((len(strikes), len(maturities)), dtype=float)
for j, T in enumerate(maturities):
    fwd = fe.ForwardSpec(S0=S0, r=r, q=q, T=float(T))
    surface[:, j] = fe.price_strip("sv32", "pyfeng_fft", strikes, fwd, params)

out = {
    "source": "Generated by scripts/generate_sv32_pyfeng_surface_reference.py",
    "reference_type": "adapter",
    "model": "sv32",
    "option_type": "call",
    "pyfeng_version": getattr(pyfeng, "__version__", "unknown"),
    "spot": S0,
    "risk_free_rate": r,
    "dividend_yield": q,
    "v0": params.v0,
    "kappa": params.kappa,
    "theta": params.theta,
    "nu": params.nu,
    "rho": params.rho,
    "maturities_years": maturities.tolist(),
    "strikes": strikes.tolist(),
    "call_price_surface": surface.tolist(),
    "pyfeng_fft_self_tolerance": 5e-4,
    "cos_improved_tolerance": 1.5e-3,
    "note": (
        "Surface shape: rows = strikes, cols = maturities. "
        "Generated with pyfeng_fft; not a printed paper table. "
        "Regenerate if pyfeng version changes significantly."
    ),
}

_OUT_PATH.write_text(json.dumps(out, indent=2) + "\n")
print(f"Written {_OUT_PATH}")
print(f"pyfeng version: {getattr(pyfeng, '__version__', 'unknown')}")
print(f"Surface (strikes x maturities):\n{surface}")
